before:
  hooks:
    - go mod tidy
    - go test ./cmd

builds:
- id: kubectl-compare
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -X 'github.com/witalisoft/kubectl-compare/cmd.Version={{.Version}}'

archives:
- builds:
  - kubectl-compare

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
