name: test
on:
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout=3m
    - name: test
      run: go test -v
      working-directory: cmd
